### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by HalfDeadPie** [MarekSuchanek/labelord_tests#35]
Dobry den, chcel by som sa spytat na problem, ktory mam. Dostavam chybovu hlasku:
`ModuleNotFoundError: No module named '__main__.labelord'; '__main__' is not a package`
Tuto chybovu hlasku dostavam ked sa snazim spustit modul
`python -m labelord run_server -h 147.32.118.51 -d`
Bez prepinača -d to funguje. Akonahle zadam -d/--debug, nastava ten problem.

Toto je obsah suboru __main__.py:
`from .labelord import main`
`main()`

a obsah suboru __init__.py
`from .labelord import cli, app`
`__all__ = ['cli', 'app']`

v labelord.py je main definovany nasledovne:
`def main():`
    `cli(obj={})`

Priecinok: labelord
Obsah: __init__.py, __main__.py, labelord.py

Preco  sa program snazi spustit z package __main__, ktory neexistuje?
Terminal ukazuje problem na riadok `from .labelord import main` v subore __main__.

**Comment by hroncok** [comment]
Zkus v souboru main použít absolutní import. Pomůže to? Debug mód flasku přenačítá modul a tohle může zlobit.

**Comment by HalfDeadPie** [comment]
Zmenil som obsah suboru __main__ na 
`from labelord.labelord import main`
`main()`

a dostal som chybovú hlášku
`ModuleNotFoundError: No module named 'labelord.labelord'; 'labelord' is not a package`

čomu úplne nechápem. Ostatne prikazy pracuju v poriadku, vratane zadania prepinaca -p/--port.

**Comment by hroncok** [comment]
Testuješ nainstalovaný package nebo máš jen kód v aktuálním adresáři?

**Comment by HalfDeadPie** [comment]
Testujem nainštalovaný package
`labelord==0.3` z pip freeze

**Comment by hroncok** [comment]
Dáš to do gitu? Vyzkouším to.

**Comment by HalfDeadPie** [comment]
Je to na githube v testovacom repozitare. Ste collaborator.

**Comment by hroncok** [comment]
Aha. Pomohlo mi ten vnitřní `labelord` modul přejmenovat na něco jiného.

Ten debug způsobuje, že se to celé pustí v podprocesu a v rámci roho podprocesu je trochu jiný `sys.path` a import vidí na cestě modul `labelord` (ten vnitřní) a v něm hledá podmodul `labelord` (protože si myslí, že je v tom vnějším) a nenajde ho.

Přidal jsem do souboru `__main__.py` na začátek toto:

```python
import sys
print(sys.path[:3])
```

A takhle to vypadá:

```console
$ python -m labelord --token "$GH_TOKEN" run_server -d
['', '/usr/lib64/python36.zip', '/usr/lib64/python3.6']
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
['.../students/stefusim__HalfDeadPie/labelord_test/labelord', '/usr/lib64/python36.zip', '/usr/lib64/python3.6']
Traceback (most recent call last):
  File ".../students/stefusim__HalfDeadPie/labelord_test/labelord/__main__.py", line 5, in <module>
    from .labelord import main
ModuleNotFoundError: No module named '__main__.labelord'; '__main__' is not a package

```

Jaká je přesně motivace té úpravy `sys.path` se přiznávám, že nevím.

**Comment by HalfDeadPie** [comment]
Priečinok labelord som premenoval na `labelord_halfdeadpie` a vykonal potrebne zmeny v suboroch. Subor `labelord.py` som premenoval na `unity.py`. Ked balicek nainstalujem do prazdneho venv a volam prikaz `labelord run_server -h 147.32.118.51 -d` (entrypoint), tak debug pracuje v pohode. Ale ak v tom istom čistom venv chcem spustiť modul pomocou python -m, mam stale ten isty problem.

```
(__venv__) D:\PYT\empty_venv>python -m labelord_halfdeadpie run_server -h 147.32.118.51 -d
['', 'D:\\PYT\\empty_venv\\__venv__\\Scripts\\python36.zip', 'C:\\Users\\simon\\AppData\\Local\\Programs\\Python\\Python36-32\\DLLs']
 * Restarting with stat
['D:\\PYT\\empty_venv\\__venv__\\lib\\site-packages\\labelord_halfdeadpie', 'D:\\PYT\\empty_venv\\__venv__\\Scripts\\python36.zip', 'C:\\Users\\simon\\AppData\\Local\\Programs\\Python\\Python36-32\\DLLs']
Traceback (most recent call last):
  File "D:\PYT\empty_venv\__venv__\lib\site-packages\labelord_halfdeadpie\__main__.py", line 3, in <module>
    from .unity import main
ModuleNotFoundError: No module named '__main__.unity'; '__main__' is not a package
```
Taktiez som dal vypisat sys.path[:3]


@

**Comment by hroncok** [comment]
zkus `from labelord_halfdeadpie.unity import main`

**Comment by HalfDeadPie** [comment]
Tak toto už zabralo, ďakujem. Môžem tento import nechať absolútny?

**Comment by hroncok** [comment]
Jasně. Někam do materiálů by to chtělo dopsat, nejspíše na konec sekce https://github.com/pyvec/naucse.python.cz/blob/master/lessons/intro/distribution/index.md#spouštění-balíčku
